name: flutter_walkthrough
description: Flutter Walkthrough Starter Kit

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  smooth_page_indicator: ^1.0.0+2
  parse_server_sdk_flutter: ^7.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  list_tile_switch: ^1.0.0

  http: any
  image_picker: ^1.0.7
  toggle_switch: ^2.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/